require("lazy").setup({
  require("plugins.which-key"),
  require("plugins.telescope"),
  require("plugins.neo-tree"),
  require("plugins.lualine"),
  require("plugins.smart-splits"),
  require("plugins.catpuccin"),
  require("plugins.nvim-treesitter"),
  require("plugins.indent-blankline"),
  require("plugins.nvim-colorizer"),
  require("plugins.alpha-nvim"),
  require("plugins.bufferline"),
  -- require("plugins.mason"),
  require("plugins.nvim-lspconfig"),
  require("plugins.dressing"),
  require("plugins.lspkind"),
  require("plugins.gitsigns"),
  require("plugins.comments"),
  require("plugins.copilot"),
  require("plugins.nvim-cmp"),
  -- require("plugins.lsp"),
})
